-- FunX Universe — Product catalog rebuild, Phase 1: clean product import
-- Run this once in the Supabase SQL editor (Project > SQL Editor > New query).
--
-- What this does, in order:
--   1. Adds the columns the new catalog needs (sku, category, age_group),
--      and renames two existing columns to match ecommerce-standard naming
--      (electronic -> is_electronic, stock -> quantity). Every other
--      existing column (images, badge, rating, reviews, video_url,
--      sort_order, is_new/is_trending/is_collectible/is_sale, box
--      dimensions, weight, line, universe, type) is left in place,
--      untouched and nullable — nothing is dropped, so a later phase can
--      still add photos/badges/ratings to these same rows without another
--      schema change.
--   2. Deletes every existing row (full replace, not a merge). This
--      cascades to `wishlists` (its product_id has ON DELETE CASCADE),
--      which is expected: old wishlist entries point at product ids that
--      won't exist after this replace anyway.
--   3. Imports all 72 rows from FunX_products_complete.csv.
--
-- This does NOT touch RLS policies (has_module('products') checks stay
-- exactly as they are — policies attach to the table, not to columns) or
-- any other table.

-- ── 1. Schema ────────────────────────────────────────────────────────────
alter table public.products rename column electronic to is_electronic;
alter table public.products rename column stock to quantity;

alter table public.products
  add column if not exists sku text,
  add column if not exists category text,
  add column if not exists age_group text;

do $$ begin
  alter table public.products add constraint products_sku_unique unique (sku);
exception when duplicate_object then null;
end $$;

-- ── 2. Full replace ──────────────────────────────────────────────────────
delete from public.products;

-- ── 3. Import ────────────────────────────────────────────────────────────
insert into public.products (id, sku, name, description, brand, category, age_group, material, color, is_electronic, price, sale_price, quantity)
values
  ('lazer-pointer-card-1', 'GD-001', 'lazer pointer card', 'The Laser Pointer Card is a compact and lightweight tool designed for presentations, classrooms, offices, and interactive activities. Its slim card-style design makes it easy to carry in your wallet, pocket, or bag. The bright laser beam provides clear visibility, making it ideal for highlighting important points during meetings or educational sessions. Built with durable materials, it is simple to use and suitable for professionals, teachers, and students alike. A practical and portable accessory for everyday use.', 'FunX', 'Novelty & Gadgets', '6+', 'ABS Plastic + Electronic Components', 'Ochre / Chrome', false, 150.0, null, 1),
  ('guitar-2', 'MU-001', 'GUITAR', 'Encourage your child''s love for music with this colorful toy guitar. Designed especially for young children, it helps improve creativity, hand-eye coordination, and musical interest through fun play. The lightweight design allows kids to hold and play comfortably, while the attractive colors make it even more exciting. Perfect for pretend performances, early music learning, and gifting on birthdays or special occasions. A wonderful toy for developing confidence and imagination.', 'FunX', 'Musical Toys', '3+', 'ABS Plastic', null, false, 0.0, null, 1),
  ('yoyo-3', 'FS-001', 'YOYO', 'High-quality metal yoyo designed for smooth spinning, stable balance, and long-lasting performance. Perfect for beginners and experienced players alike, this yoyo helps improve hand-eye coordination while making tricks easier and more enjoyable. Its premium finish and durable construction make it a great choice for daily practice or as a fun gift for kids and adults.', 'FunX', 'Fidget & Skill Toys', null, null, null, false, 0.0, null, 2),
  ('zoo-bird-case-4', 'AC-001', 'ZOO BIRD CASE', 'The Zoo Bird Case features a fun and colorful animal-inspired design that children will love. Made from durable and child-friendly materials, it is perfect for storing stationery, toys, art supplies, or other small essentials. Its lightweight construction makes it easy for kids to carry wherever they go. The attractive design encourages organization while adding a playful touch to everyday use. A practical and stylish storage solution for home, school, or travel.', 'FunX', 'Bags & Accessories', '3+', 'Plastic / Fabric', null, false, 615.0, null, 2),
  ('avengers-characters-5', 'AF-001', 'Avengers characters', 'Bring superhero adventures to life with these Avengers character figures. Designed with vibrant colors and detailed finishing, these action figures inspire imaginative role play and storytelling. Children can recreate their favorite superhero scenes or build their own exciting adventures. Made from durable materials, these collectible figures are suitable for playtime, display, or gifting. An excellent choice for Marvel fans of all ages', 'FunX', 'Action Figures', '3+', 'PVC Plastic', null, false, 385.0, null, 3),
  ('abc-puzzle-mat-6', 'ED-001', 'ABC puzzle mat', 'Help your child learn while having fun with the ABC Puzzle Mat. Made from soft EVA foam, this colorful floor mat introduces children to letters, shapes, and colors through interactive play. It provides a comfortable and safe surface for crawling, playing, and learning. Easy to assemble and clean, the puzzle pieces encourage problem-solving skills, creativity, and early educational development. Perfect for nurseries, classrooms, and playrooms.', 'FunX', 'Educational Toys', '2+', 'EVA Foam', null, false, 375.0, null, 1),
  ('182-pcs-tray-7', 'BB-001', '182 pcs tray', 'This 182-piece building block set offers endless opportunities for creative construction and imaginative play. Packed in a convenient storage tray, it helps keep all pieces organized after playtime. The colorful blocks easily connect together, allowing children to build houses, vehicles, towers, and many other exciting creations. Playing with building blocks improves fine motor skills, concentration, creativity, and logical thinking. A great educational toy for growing minds.', 'FunX', 'Building Blocks', '5+', 'ABS Plastic', null, false, 365.0, null, 1),
  ('sg-toys-blocks-8', 'BB-002', 'sg toys blocks', 'SG Toys Blocks are designed to inspire creativity and imagination in children of all ages. The colorful pieces fit together smoothly, allowing kids to create unique structures, buildings, and vehicles. These blocks help improve hand-eye coordination, problem-solving abilities, and fine motor skills while providing hours of educational entertainment. Made from child-safe materials, they are ideal for home, classrooms, and learning centers.', 'FunX', 'Building Blocks', '3+', 'ABS Plastic', null, false, 360.0, null, 1),
  ('uno-flip-card-9', 'GM-001', 'uno flip card', 'UNO Flip Card is an exciting twist on the classic UNO game, featuring double-sided cards that make every round more challenging and entertaining. Easy to learn yet full of surprises, it is perfect for family game nights, parties, and gatherings. Suitable for children and adults, this fast-paced card game improves strategic thinking, quick decision-making, and social interaction. A must-have game for endless family fun.', 'FunX', 'Games & Puzzles', '7+', 'Paper Card + Plastic Coating', null, false, 280.0, null, 3),
  ('building-block-bag-10', 'BB-003', 'building block bag', 'The Building Block Bag includes colorful construction blocks packed in a convenient carrying bag for easy storage and travel. Children can create countless structures using their imagination while developing creativity, hand-eye coordination, and problem-solving skills. The durable blocks are easy to connect and separate, making them suitable for young builders. Ideal for educational play at home, daycare centers, and classrooms.', 'FunX', 'Building Blocks', '3+', 'ABS Plastic + Storage Bag', null, false, 375.0, null, 1),
  ('baby-rattle-11', 'BT-001', 'baby rattle', 'Keep your little one entertained with this colorful Baby Rattle designed to stimulate sensory development and early learning. Its lightweight design is easy for tiny hands to hold, encouraging grasping and hand movement. Gentle rattling sounds help improve hearing awareness while bright colors capture your baby''s attention. Made from child-safe materials with smooth edges, it is perfect for everyday play and early childhood development.', 'FunX', 'Baby Toys', '0-2', 'ABS Plastic', null, false, 350.0, null, 1),
  ('jenga-game-small-12', 'GM-002', 'jenga game small', 'Enjoy endless family fun with the Small Jenga Game, a classic wooden block stacking game designed to improve concentration, balance, and strategic thinking. Players carefully remove one block at a time without letting the tower fall, creating exciting moments for children and adults alike. Made from durable, smooth-finished wood, this compact version is easy to carry for travel, parties, and family gatherings. A perfect educational game that promotes patience, coordination, and problem-solving skills.', 'FunX', 'Games & Puzzles', '6+', 'Wooden Blocks', null, false, 650.0, null, 1),
  ('jenga-game-large-13', 'GM-003', 'jenga game large', 'Take game night to the next level with the Large Jenga Game. Featuring larger wooden blocks for a more exciting experience, this game is ideal for family gatherings, parties, schools, and outdoor events. Each block is crafted with smooth edges for safe handling and long-lasting durability. Playing Jenga helps improve hand-eye coordination, focus, patience, and teamwork while providing hours of fun for players of all ages.', 'FunX', 'Games & Puzzles', '6+', 'Wooden Blocks', null, false, 1700.0, null, 1),
  ('telescope-14', 'ED-002', 'telescope', 'Introduce children to the exciting world of exploration with this educational toy telescope. Designed for young learners, it encourages curiosity about nature, astronomy, and outdoor adventures. Its lightweight construction makes it easy for kids to handle, while the realistic design inspires imaginative learning experiences. Perfect for educational activities, science projects, and pretend adventures, this telescope makes learning both fun and engaging.', 'FunX', 'Educational Toys', '6+', 'ABS Plastic + Optical Lens', null, false, 505.0, null, 1),
  ('rc-spray-car-15', 'RC-001', 'RC spray car', 'Experience next-level racing excitement with the RC Spray Car. This remote control vehicle features realistic mist spray effects, bright LED lights, and smooth controls that create an exciting driving experience. Built from durable, child-safe materials, it performs well on different indoor surfaces while encouraging hand-eye coordination and motor skill development. A perfect gift for children who love remote control cars and action-packed adventures.', 'FunX', 'Remote Control Vehicles', '6+', 'ABS Plastic + Electronic Components', null, false, 2750.0, null, 1),
  ('kids-time-clock-bag-16', 'AC-002', 'kids time clock bag', 'The Kids Time Clock Bag combines a fun clock-inspired design with everyday practicality. Lightweight and comfortable to carry, it is perfect for school, outings, travel, or daily use. The spacious compartment provides room for small toys, snacks, stationery, or personal belongings. Designed with adjustable straps and colorful styling, this bag is both fashionable and functional, making it a favorite accessory for young children.', 'FunX', 'Bags & Accessories', '3+', 'Fabric + Plastic', null, false, 2000.0, null, 1),
  ('educational-puzzle-foam-17', 'ED-003', 'educational puzzle foam', 'Make learning enjoyable with the Educational Puzzle Foam Set. Crafted from soft, high-quality EVA foam, this puzzle helps children recognize letters, numbers, colors, and shapes while developing problem-solving skills. The lightweight pieces are easy to assemble and safe for young learners. Perfect for nurseries, classrooms, and home learning, this educational toy encourages creativity, early development, and interactive play in a fun environment.', 'FunX', 'Educational Toys', '2+', 'EVA Foam', null, false, 690.0, null, 1),
  ('8-5-lcd-writing-tablet-18', 'ED-004', '8.5 lcd writing tablet', 'The 8.5-inch LCD Writing Tablet offers an eco-friendly alternative to paper for writing, drawing, and learning. Its pressure-sensitive screen creates smooth writing without ink, chalk, or markers. Simply press the erase button to clear the screen instantly and start again. Lightweight and portable, it is perfect for children, students, and travelers. Ideal for practicing handwriting, sketching, note-taking, and creative play anytime, anywhere.', 'FunX', 'Educational Toys', '3+', 'ABS Plastic + LCD Screen', null, false, 210.0, null, 3),
  ('12-lcd-writing-tablet-19', 'ED-005', '12 lcd writing tablet', 'Designed with a larger display, the 12-inch LCD Writing Tablet provides more space for writing, drawing, and educational activities. The reusable screen helps reduce paper waste while offering a fun and convenient learning experience. Its lightweight design makes it easy to carry to school, home, or travel. Suitable for children and adults, it is perfect for note-taking, practicing handwriting, doodling, and creative expression.', 'FunX', 'Educational Toys', '3+', 'ABS Plastic + LCD Screen', null, false, 400.0, null, 2),
  ('fashion-frozen-doll-20', 'DL-001', 'fashion frozen doll', 'Delight your child with this beautiful Fashion Frozen Doll inspired by a magical princess theme. Featuring elegant clothing, attractive colors, and charming details, this doll encourages imaginative storytelling and creative role play. Children can create endless adventures while developing communication skills and creativity. Made from quality materials with an eye-catching design, it makes a wonderful birthday or holiday gift for young doll lovers.', 'FunX', 'Dolls & Doll Houses', '3+', 'PVC Plastic + Fabric', null, false, 1225.0, null, 1),
  ('fashion-frozen-doll-single-21', 'DL-002', 'fashion frozen doll single', 'The Fashion Frozen Doll Single is a beautifully designed princess-inspired doll featuring stylish clothing and attractive detailing. Lightweight and easy to handle, it is perfect for pretend play, storytelling, and imaginative adventures. Crafted from durable, child-friendly materials, this doll offers hours of entertainment while encouraging creativity and social development. A lovely addition to any doll collection and an ideal gift for children.', 'FunX', 'Dolls & Doll Houses', '3+', 'PVC Plastic + Fabric', null, false, 1050.0, null, 1),
  ('kids-air-pillow-22', 'AC-003', 'kids air pillow', 'Give your child extra comfort during travel with the Kids Air Pillow. Designed with soft, inflatable support, this lightweight pillow helps reduce neck strain during long journeys by car, bus, train, or airplane. It inflates quickly and folds into a compact size for easy storage when not in use. Made from durable, child-friendly material, it''s perfect for vacations, school trips, naps, and everyday travel.', 'FunX', 'Bags & Accessories', '3+', 'PVC + Soft Fabric', null, false, 395.0, null, 2),
  ('51-pcs-blocks-bag-23', 'BB-004', '51 pcs blocks bag', 'Inspire creativity with the 51 PCS Blocks Bag, featuring colorful building blocks that encourage imaginative play and early learning. The easy-to-connect pieces allow children to build houses, vehicles, towers, and countless other designs. Packed in a convenient carrying bag, the set is easy to store and transport. This educational toy helps improve fine motor skills, hand-eye coordination, creativity, and problem-solving abilities.', 'FunX', 'Building Blocks', '3+', 'ABS Plastic', null, false, 160.0, null, 3),
  ('magnatic-blocks-small-24', 'BB-005', 'magnatic blocks small', 'The Small Magnetic Blocks Set offers a fun and educational building experience for young learners. Each colorful block connects easily using strong magnets, allowing children to create endless structures and shapes. This interactive toy encourages STEM learning, logical thinking, creativity, and hand-eye coordination. Made from high-quality, child-safe materials with smooth edges, it provides safe and enjoyable play for hours.', 'FunX', 'Building Blocks', '3+', 'ABS Plastic + Magnets', null, false, 650.0, null, 3),
  ('magnatic-blocks-large-25', 'BB-006', 'magnatic blocks large', 'Build bigger and better creations with the Large Magnetic Blocks Set. Featuring larger magnetic pieces that are easy for little hands to hold, this educational toy promotes creativity, spatial awareness, and problem-solving skills. Children can design buildings, vehicles, and unique structures while developing fine motor skills. Made from durable, non-toxic materials, it''s an excellent learning toy for home, classrooms, and play areas.', 'FunX', 'Building Blocks', '3+', 'ABS Plastic + Magnets', null, false, 965.0, null, 1),
  ('doctor-toy-set-26', 'RP-001', 'doctor toy set', 'Let children explore the world of healthcare through imaginative play with this Doctor Toy Set. Complete with realistic medical accessories, the set encourages role-playing while helping children become familiar with common medical tools. It promotes creativity, communication, confidence, and social interaction. Manufactured from child-safe materials with smooth edges, it''s an ideal educational gift for boys and girls who enjoy pretend play.', 'FunX', 'Role Play & Pretend Play', '3+', 'ABS Plastic', null, false, 540.0, null, 2),
  ('sword-27', 'RP-002', 'sword', 'Bring adventure to life with this lightweight toy sword designed for imaginative role play. Whether playing as a brave knight, superhero, or warrior, children can enjoy hours of creative storytelling and active fun. Made from durable, child-friendly materials with smooth edges, it is safe for pretend battles and costume events. A great accessory for imaginative games and themed parties.', 'FunX', 'Role Play & Pretend Play', '3+', 'ABS Plastic', null, false, 2250.0, null, 1),
  ('educational-blocks-28', 'ED-006', 'educational blocks', 'Support your child''s early learning journey with these Educational Blocks. Designed to help children recognize letters, numbers, colors, and shapes, this colorful block set combines education with fun. Building and arranging the blocks improves hand-eye coordination, problem-solving skills, and creativity while encouraging independent learning. Perfect for preschool education, home learning, and classroom activities.', 'FunX', 'Educational Toys', '3+', 'ABS Plastic', null, false, 685.0, null, 1),
  ('mama-baba-rattle-120pcs-29', 'BT-002', 'mama baba rattle 120pcs', 'The Mama Baba Rattle 120 PCS Pack is a bulk collection of colorful baby rattles suitable for retailers, gift packs, daycare centers, and baby stores. Each rattle is designed to stimulate a baby''s hearing, vision, and grasping abilities through gentle sounds and vibrant colors. Made from child-safe materials, these rattles provide safe entertainment while supporting early sensory development', 'FunX', 'Baby Toys', '0-2', 'ABS Plastic', null, false, 960.0, null, 1),
  ('stick-block-30', 'BB-007', 'stick block', 'Encourage creativity and engineering skills with the Stick Block construction set. Children can connect the colorful sticks and connectors to create unique shapes, buildings, vehicles, and imaginative designs. This educational toy enhances problem-solving, logical thinking, hand-eye coordination, and fine motor skills while keeping children entertained for hours. Made from durable, child-safe materials for long-lasting educational fun.', 'FunX', 'Building Blocks', '3+', 'ABS Plastic', null, false, 560.0, null, 1),
  ('small-wheel-building-block-31', 'BB-008', 'small wheel building block', 'The Small Wheel Building Block Set allows children to build exciting moving vehicles and creative models using colorful construction pieces and wheels. This interactive toy encourages imagination, engineering skills, and creative thinking while improving fine motor development and coordination. Easy to assemble and designed with child-safe materials, it''s perfect for home learning, classroom activities, and fun family playtime.', 'FunX', 'Building Blocks', '3+', 'ABS Plastic + Rubber Wheels', null, false, 450.0, null, 2),
  ('makeup-box-32', 'RP-003', 'makeup box', 'Let your child enjoy hours of imaginative role play with this beautiful Makeup Box playset. Designed with realistic beauty accessories, it encourages creativity, confidence, and social interaction while providing a safe pretend makeup experience. Made from durable, child-friendly materials with smooth edges, this set is perfect for dress-up games, parties, and everyday fun. A wonderful gift for young children who love fashion and pretend play.', 'FunX', 'Role Play & Pretend Play', '3+', 'ABS Plastic', null, false, 1500.0, null, 2),
  ('dartboard-game-33', 'GM-004', 'dartboard game', 'Make indoor play more exciting with this Dartboard Game, designed for safe family entertainment. It helps improve hand-eye coordination, focus, accuracy, and motor skills while providing hours of competitive fun. The child-friendly design makes it suitable for both kids and adults to enjoy together. Ideal for homes, schools, parties, and game rooms, this classic target game encourages active and engaging play.', 'FunX', 'Games & Puzzles', '6+', 'Plastic + Fabric/Board Material', null, false, 1160.0, null, 1),
  ('pistol-34', 'RP-004', 'pistol', 'The Toy Pistol is designed for exciting pretend play and imaginative adventures. Its lightweight construction and child-safe design make it easy for young children to handle comfortably. Whether playing as a police officer, hero, or action character, kids can enjoy creative storytelling while developing social and communication skills. Built from durable materials, it offers long-lasting entertainment for indoor and outdoor play.', 'FunX', 'Role Play & Pretend Play', '3+', 'ABS Plastic', null, false, 400.0, null, 2),
  ('tool-tray-35', 'RP-005', 'TOOL TRAY', 'Encourage hands-on learning with this Tool Tray playset featuring a collection of realistic toy tools neatly stored in a portable tray. Children can enjoy pretend repair work while improving creativity, hand-eye coordination, and problem-solving skills. Made from durable, child-safe materials, this educational toy supports imaginative role play and introduces kids to basic construction concepts in a fun and engaging way.', 'FunX', 'Role Play & Pretend Play', '3+', 'ABS Plastic', null, false, 400.0, null, 2),
  ('mama-baba-rattle-8pcs-36', 'BT-003', 'mama baba rattle 8pcs', 'The Mama Baba Rattle 8 PCS Set includes eight colorful baby rattles specially designed to support early sensory development. Each rattle produces gentle sounds that stimulate hearing while encouraging grasping and hand movement. Crafted from safe, non-toxic materials with smooth edges, this set is ideal for newborns and infants. A perfect gift choice for baby showers, birthdays, or everyday play.', 'FunX', 'Baby Toys', '0-2', 'ABS Plastic', null, false, 960.0, null, 1),
  ('mama-baba-rattle-5pcs-37', 'BT-004', 'mama baba rattle 5pcs', 'Keep your little one entertained with the Mama Baba Rattle 5 PCS Set. This colorful collection of baby rattles helps develop sensory awareness, motor skills, and hand-eye coordination through fun interactive play. Lightweight and easy to hold, each rattle is made from child-safe materials for comfortable everyday use. An excellent early learning toy for infants and toddlers.', 'FunX', 'Baby Toys', '0-2', 'ABS Plastic', null, false, 960.0, null, 1),
  ('mr-doll-house-38', 'DL-003', 'mr doll house', 'Create magical stories with the MR Doll House playset. Featuring beautifully designed rooms and detailed accessories, this doll house encourages imaginative role play and creative storytelling. Children can decorate, arrange furniture, and create endless adventures while developing communication, creativity, and social skills. Made from quality materials with attractive detailing, it makes a perfect gift for children who love doll house play.', 'FunX', 'Dolls & Doll Houses', '3+', 'ABS Plastic', null, false, 615.0, null, 1),
  ('tesla-car-39', 'DC-001', 'tesla car', 'Inspired by the sleek design of modern electric vehicles, the Tesla Toy Car offers realistic styling and durable construction for endless fun. Its smooth wheels and attractive finish make it ideal for imaginative play, collections, and display. Children can enjoy exciting racing adventures while improving coordination and creativity. A stylish toy car suitable for kids and automobile enthusiasts alike.', 'FunX', 'Die-Cast Vehicles', '3+', 'ABS Plastic + Rubber Wheels', null, false, 3000.0, null, 1),
  ('bowling-game-40', 'GM-005', 'bowling game', 'Bring the excitement of bowling into your home with this complete Bowling Game Set. Designed for children and families, it helps improve balance, coordination, concentration, and motor skills through active play. Easy to set up and suitable for indoor use, this colorful game provides hours of healthy entertainment while encouraging friendly competition. A great choice for family game nights and children''s activities.', 'FunX', 'Games & Puzzles', '3+', 'Plastic', null, false, 800.0, null, 1),
  ('barbie-kitchen-41', 'RP-006', 'barbie kitchen', 'The Barbie Kitchen Playset allows children to enjoy fun cooking adventures through imaginative role play. Featuring colorful kitchen accessories and realistic details, it encourages creativity, communication, and storytelling. Children can pretend to prepare meals, organize kitchen items, and create exciting cooking experiences. Made from child-safe materials, this educational toy is perfect for developing social skills while having endless fun.', 'FunX', 'Role Play & Pretend Play', '3+', 'ABS Plastic', null, false, 2050.0, null, 1),
  ('rivalry-rc-car-42', 'RC-002', 'Rivalry rc car', 'Experience high-speed excitement with the Rivalry RC Car, designed for thrilling remote-control racing adventures. Featuring responsive controls, durable construction, and smooth performance, this RC car delivers hours of entertainment for children and hobby enthusiasts. Its stylish design and reliable handling make it suitable for both indoor and outdoor play. An excellent gift for kids who love action-packed racing toys.', 'FunX', 'Remote Control Vehicles', '6+', 'ABS Plastic + Rubber + Electronic Components', null, false, 2950.0, null, 1),
  ('travel-pillow-43', 'AC-004', 'travel pillow', 'Travel comfortably wherever you go with this soft and supportive Travel Pillow. Designed to provide excellent neck support during long journeys, it helps reduce discomfort while traveling by car, bus, train, or airplane. Made from comfortable, durable materials, the pillow is lightweight, portable, and easy to carry. A practical travel accessory for children and adults seeking extra comfort on every trip.', 'FunX', 'Bags & Accessories', '3+', 'Memory Foam + Soft Fabric', null, false, 395.0, null, 2),
  ('gyro-44', 'FS-002', 'GYRO', 'Enjoy endless spinning fun with the Gyro toy, designed to entertain while improving focus, balance, and hand-eye coordination. Its smooth spinning action helps children develop motor skills and concentration through interactive play. Made from durable, child-safe materials, this classic toy is lightweight, portable, and suitable for home, school, or outdoor activities. A fun educational toy for children of all ages.', 'FunX', 'Fidget & Skill Toys', '6+', 'ABS Plastic + Metal Components', null, false, 625.0, null, 2),
  ('lateral-stunt-car-45', 'RC-003', 'lateral stunt car', 'Take remote-control action to the next level with the Lateral Stunt Car. Designed for 360-degree spins, side drifting, flips, and exciting stunt movements, this advanced RC vehicle delivers an unforgettable driving experience. Built from durable materials with powerful performance, it is suitable for both indoor and outdoor adventures. A perfect gift for kids who love high-speed stunt cars and thrilling action.', 'FunX', 'Remote Control Vehicles', '6+', 'ABS Plastic + Rubber + Electronic Components', null, false, 3500.0, null, 1),
  ('oil-spray-bottle-46', 'HH-001', 'oil spray bottle', 'The Oil Spray Bottle is a convenient kitchen accessory designed for healthy cooking and precise oil application. Ideal for grilling, baking, roasting, air frying, and salad preparation, it provides an even mist that helps reduce excess oil usage. Made from durable, food-grade materials, it is easy to refill, clean, and use daily. A practical addition to every modern kitchen.', 'FunX', 'Household & Lifestyle', '18+', 'Food Grade Plastic', null, false, 450.0, null, 2),
  ('blender-47', 'HH-002', 'Blender', 'Prepare fresh smoothies, juices, milkshakes, and protein drinks with this portable Blender. Designed for convenience and efficiency, it features powerful blending performance in a compact, lightweight design that''s easy to carry anywhere. Ideal for home, office, gym, or travel use, it is simple to operate and easy to clean. A perfect choice for anyone who enjoys fresh and healthy beverages on the go.', 'FunX', 'Household & Lifestyle', '18+', 'ABS Plastic + Stainless Steel Blades', null, false, 1000.0, null, 2),
  ('vaccum-cup-coffee-48', 'HH-003', 'vaccum cup coffee', 'Keep your favorite beverages at the perfect temperature with this premium Vacuum Cup Coffee Mug. Made from high-quality stainless steel with double-wall vacuum insulation, it keeps drinks hot or cold for extended hours. The leak-resistant lid and comfortable grip make it ideal for travel, office, gym, or everyday use. Stylish, durable, and reusable, this insulated coffee cup is a must-have for tea and coffee lovers.', 'FunX', 'Household & Lifestyle', '12+', 'Stainless Steel + Plastic Lid', null, false, 950.0, null, 2),
  ('stuff-toys-49', 'PL-001', 'stuff toys', null, 'FunX', 'Plush Toys', '0+', null, null, false, 0.0, null, 0),
  ('spiderman-50', 'AF-002', 'spiderman', null, 'FunX', 'Action Figures', '0+', 'Plush Fabric / PVC Plastic', null, false, 1050.0, null, 1),
  ('teddy-bear-51', 'PL-002', 'teddy bear', null, 'FunX', 'Plush Toys', '0+', 'Plush Fabric + PP Cotton Filling', null, false, 2495.0, null, 1),
  ('hanging-52', 'PL-003', 'hanging', null, 'FunX', 'Plush Toys', '0+', 'Plush Fabric / Plastic', null, false, 385.0, null, 5),
  ('emoji-pillow-53', 'PL-004', 'emoji pillow', null, 'FunX', 'Plush Toys', '0+', 'Plush Fabric + PP Cotton Filling', null, false, 350.0, null, 3),
  ('keychains-54', 'KC-001', 'KEYCHAINS', null, 'FunX', 'Keychains', '6+', null, null, false, 0.0, null, 0),
  ('bottle-55', 'AC-005', 'BOTTLE', null, 'FunX', 'Bags & Accessories', null, 'Plastic / Stainless Steel', null, false, 40.0, null, 12),
  ('100-56', 'KC-002', '100', 'Add a fun and stylish touch to your belongings with the 100 Keychain. Designed with an attractive look and lightweight construction, it is perfect for attaching to keys, backpacks, handbags, and accessories. Its unique design makes it a great collectible item and a perfect small gift option for kids and teenagers. Durable and easy to carry, this keychain combines style with everyday usefulness.', 'FunX', 'Keychains', null, 'PVC + Metal Ring', null, false, 70.0, null, 12),
  ('tom-nd-jerry-57', 'KC-003', 'TOM ND JERRY', 'Bring your favorite cartoon memories everywhere with this Tom & Jerry Keychain. Featuring the iconic cartoon character design, it adds a playful and charming look to keys, bags, and backpacks. Made with lightweight and durable material, it is easy to carry and perfect for cartoon lovers. A cute accessory and a great gifting choice for children and fans of classic cartoons.', 'FunX', 'Keychains', null, 'PVC / Plush Fabric + Metal Ring', null, false, 100.0, null, 11),
  ('unicorn-58', 'KC-004', 'UNICORN', 'Make your accessories more colorful with this adorable Unicorn Keychain. Designed with a cute and magical unicorn theme, it is perfect for decorating school bags, handbags, keys, and personal items. Its lightweight design makes it convenient to carry, while the attractive appearance makes it a favorite among kids. A lovely gift choice for unicorn lovers and collectors.', 'FunX', 'Keychains', null, 'Plush Fabric + Metal Ring', null, false, 70.0, null, 12),
  ('mirror-59', 'KC-005', 'MIRROR', 'The Mirror Keychain is a stylish and practical accessory that combines beauty with convenience. Featuring a compact mirror design, it can easily attach to handbags, purses, or key rings for quick use anytime. Its portable size makes it perfect for travel and daily carrying. A useful and fashionable accessory for girls and women.', 'FunX', 'Keychains', null, 'Plastic + Mirror Glass', null, false, 60.0, null, 9),
  ('moody-60', 'KC-006', 'MOODY', 'Express your mood with this unique Moody Keychain featuring a fun and attractive design. Perfect for decorating bags, backpacks, and keys, it adds personality to your everyday accessories. Made with lightweight materials, it is easy to carry and suitable for gifting. A trendy collectible item for kids and young accessory lovers.', 'FunX', 'Keychains', null, 'PVC + Metal Ring', null, false, 140.0, null, 6),
  ('emojis-61', 'KC-007', 'EMOJIS', 'Bring fun and emotions to your accessories with this colorful Emoji Keychain. Featuring popular emoji expressions, it adds a cheerful and stylish touch to keys, bags, and backpacks. Lightweight, durable, and easy to attach, it is perfect for everyday use and gifting. A fun accessory for kids, teenagers, and emoji fans.', 'FunX', 'Keychains', null, 'PVC + Metal Ring', null, false, 50.0, null, 11),
  ('garebox-62', 'KC-008', 'GAREBOX', 'The Gearbox Keychain is a creative and stylish accessory designed for vehicle and gadget lovers. Featuring an attractive mechanical-inspired design, it adds a unique touch to keys, bags, and collections. Compact and lightweight, it is easy to carry and makes an excellent gift option for enthusiasts who love unique accessories.', 'FunX', 'Keychains', null, 'PVC + Metal Ring', null, false, 120.0, null, 12),
  ('food-63', 'KC-009', 'FOOD', 'Add a fun food-inspired style to your accessories with this Fast Food Keychain. Designed with cute fast-food themes, it is perfect for decorating backpacks, handbags, and key rings. Its colorful appearance makes it attractive for kids and collectors. A small yet creative accessory that also works as a unique gift item.', 'FunX', 'Keychains', null, 'PVC + Metal Ring', null, false, 75.0, null, 12),
  ('lazers-led-lights-64', 'LD-001', 'LAZERS LED LIGHTS', 'Create an exciting atmosphere with these Lazers LED Lights. Featuring bright and colorful lighting effects, they are perfect for parties, rooms, gaming setups, events, and decoration. Easy to use and visually attractive, these LED lights add a modern and stylish look to any space. A great choice for creating a fun and vibrant environment.', 'FunX', 'Décor & Lighting', null, 'Plastic + LED Components', null, false, 220.0, null, 12),
  ('rivalry-car-65', 'DC-002', 'RIVALRY CAR', 'Experience exciting racing adventures with the Rivalry Car. Designed with a stylish appearance and durable construction, it provides children with hours of fun and imaginative play. Its attractive design makes it perfect for car enthusiasts and toy collectors. A great gift option for kids who love vehicles, racing, and action-packed entertainment.', 'FunX', 'Die-Cast Vehicles', null, 'ABS Plastic + Rubber Wheels', null, false, 2950.0, null, 1),
  ('bowling-game-66', 'GM-006', 'BOWLING GAME', 'Bring the fun of bowling into your home with this entertaining Bowling Game Set. Designed for children and family play, it helps improve focus, balance, hand-eye coordination, and motor skills. Easy to set up and enjoyable for all ages, it is perfect for indoor activities, parties, and family gatherings. A great way to enjoy active and exciting gameplay anytime.', 'FunX', 'Games & Puzzles', null, 'Plastic', null, false, 800.0, null, 1),
  ('boxing-kit-67', 'GM-007', 'boxing kit', 'Introduce children to fun and active play with this Boxing Kit. Designed for safe pretend boxing practice, it includes accessories that encourage physical activity, coordination, and confidence. It helps children develop focus, movement skills, and sports interest while enjoying exciting playtime. Made with comfortable and child-friendly materials, it is a great gift for young sports lovers.', 'FunX', 'Games & Puzzles', null, 'PU Foam + Fabric', null, false, 785.0, null, 1),
  ('antique-cars-68', 'DC-003', 'antique cars', null, 'FunX', 'Die-Cast Vehicles', '3+', null, null, false, 0.0, null, 0),
  ('ford-rapter-69', 'DC-004', 'Ford Rapter', 'Experience the powerful look of the Ford Raptor toy car, inspired by the famous off-road pickup design. Featuring realistic details, attractive styling, and durable construction, it is perfect for children who love adventure vehicles. This miniature model encourages imaginative racing and outdoor exploration play while also making a great collectible item for car lovers.', 'FunX', 'Die-Cast Vehicles', '6+', 'Die Cast Metal + Plastic Parts', null, false, 1200.0, null, 1),
  ('rolls-royce-70', 'DC-005', 'rolls royce', 'Enjoy luxury-inspired design with this Rolls Royce miniature toy car. Featuring an elegant appearance and realistic detailing, it brings the beauty of a premium vehicle into a compact collectible form. Perfect for kids'' imaginative play, car collections, and decoration, this stylish toy makes a great gift for automobile fans and collectors.', 'FunX', 'Die-Cast Vehicles', null, 'Die Cast Metal + Plastic Parts', null, false, 1200.0, null, 1),
  ('lzxvs-71', 'DC-006', 'lzxvs', 'The LZXVS toy/product features an attractive design with fun and engaging details for children and collectors. Designed for entertainment and creative play, it provides an enjoyable experience while adding variety to your toy collection. Its unique appearance makes it a suitable choice for gifting and everyday fun.', 'FunX', 'Die-Cast Vehicles', null, 'Die Cast Metal + Plastic Parts', null, false, 1200.0, null, 1),
  ('skateboard-72', 'OS-001', 'skateboard', 'Enjoy outdoor fun and active play with this Skateboard. Designed for beginners and young riders, it helps improve balance, coordination, and confidence while providing an exciting experience. Featuring a durable board design and smooth movement, it is suitable for recreational use and learning new skills. A perfect choice for kids who enjoy adventure and outdoor activities.', 'FunX', 'Outdoor & Sports', null, 'Wood + PU Wheels + Metal Axle', null, false, 1200.0, null, 1);

